wandb_version: 1

C:
  desc: null
  value: 1
_wandb:
  desc: null
  value:
    cli_version: 0.8.36
    code_path: code/wifi_class_keras.py
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.10
    session_history: code/_session_history.ipynb
gamma:
  desc: null
  value: auto
seed:
  desc: null
  value: 0
